server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: ${xiaoyu.datasource.driver-class-name}
    url: jdbc:mysql://${xiaoyu.datasource.host}:${xiaoyu.datasource.port}/${xiaoyu.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8mb4&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${xiaoyu.datasource.username}
    password: ${xiaoyu.datasource.password}
  data:
    redis:
      host: ${xiaoyu.redis.host}
      port: ${xiaoyu.redis.port}
      password: ${xiaoyu.redis.password}
      database: ${xiaoyu.redis.database}
  rabbitmq:
    host: ${xiaoyu.rabbitmq.host:localhost}
    port: ${xiaoyu.rabbitmq.port:5672}
    username: ${xiaoyu.rabbitmq.username:guest}
    password: ${xiaoyu.rabbitmq.password:guest}
    virtual-host: ${xiaoyu.rabbitmq.virtual-host:/}
    connection-timeout: 15000
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaoyu.entity
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      xiaoyu:
        mapper: debug
        service: info
        controller: info
        utils: info

xiaoyu:
  jwt:
    admin-secret-key: "xiao yu"
    admin-ttl: 7200000
    admin-token-name: token

aliyun:
  oss:
    access-key-id: ${xiaoyu.oss.access-key-id}
    access-key-secret: ${xiaoyu.oss.access-key-secret}
    endpoint: ${xiaoyu.oss.endpoint}
    bucket-name: ${xiaoyu.oss.bucket-name}
    domain: ${xiaoyu.oss.domain}
    path-prefix: xiaoyu/
    max-file-size: 10485760
    allowed-types:
      - jpg
      - jpeg
      - png
      - gif
      - bmp
      - webp
      - mp4
      - avi
      - mov
      - mp3
      - wav
      - pdf
      - doc
      - docx
      - txt