xiaoyu:
  datasource:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:3306}
    database: ${DB_NAME:xiaoyu}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DB:0}
  oss:
    access-key-id: ${OSS_ACCESS_KEY_ID:your_access_key_id}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET:your_access_key_secret}
    endpoint: ${OSS_ENDPOINT:oss-cn-hangzhou.aliyuncs.com}  # 根据你的区域修改
    bucket-name: ${OSS_BUCKET:your_bucket_name}
    domain: ${OSS_DOMAIN:https://your_bucket_name.oss-cn-hangzhou.aliyuncs.com}  # 或者你的自定义域名